name: WASM

on:
  push:
  pull_request:
  schedule:
    - cron: "35 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add target
        run: rustup target add wasm32-unknown-unknown
      - name: Run build
        run: cargo build --verbose
      - name: Setup emsdk with cache
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 1.38.40
          actions-cache-folder: 'emsdk-cache'
      - name: Install vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git vcp
          vcp/bootstrap-vcpkg.sh
      - name: Run integration tests
        run: |
          tests/wasm.sh
